version: "3.9"
services:
  app:
    image: askebakken-app
    ports:
      - "80:80"
        
  graphql:
    image: askebakken-graphql
    ports:
      - "5132:80"
    depends_on:
      - mongo
    env_file:
      - .env
  
  mongo:
    image: mongo:latest
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:

